# Generated by Django 3.1.4 on 2020-12-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='song',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
